# Generated by Django 6.0.4 on 2026-04-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmenu',
            old_name='intventory',
            new_name='inventory',
        ),
    ]
