# Generated by Django 6.0.4 on 2026-04-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_intventory_bookmenu_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmenu',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
